- YoutubeExplode/Services/DefaultRequestService.cs
Even using the 'HEAD' verb, the HttpClient tries to allocate a buffer for the Content. Adding HttpCompletionOption.ResponseHeadersRead parameter tells the HttpClient not to do this.
> The SendAsync method fails when Content-Length is > 2GB.

- YoutubeExplode/Services/DefaultRequestService.cs
- YoutubeExplode/YoutubeClient.cs
ConfigureAwait(false) allows a method to continue on a different thread it was first called on. This is very minor improvement but is it in general a good idea to use this in libraries.
Here some more info on ConfigureAwait: https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Async-library-methods-should-consider-using-Task-ConfigureAwait-false-
> Added ConfigureAwait(false) to all awaited Tasks

- YoutubeExplode/Exceptions/VideoRequiresPurchaseException.cs
- YoutubeExplode/YoutubeClient.cs
I added a `VideoRequiresPurchaseException` which is thrown when the video requires a purchase. If so, we have no access to most video details. [Example video](https://www.youtube.com/watch?v=p3dDcKOFXQg)
> Throw exception for YouTube Red videos

- YoutubeExplode/YoutubeClient.cs
Some playlists like WatchLater (WL), maybe other private playlists as well, do not contain the views element in the metadata.
So I made it optional in GetPlaylistInfoAsync.
> Views element is optional sometimes in playlist metadata

- YoutubeExplode.Tests/Data.cs
- YoutubeExplode/Internal/HttpClientEx.cs
- YoutubeExplode/YoutubeClient.Video.cs
Fixes https://github.com/Tyrrrz/YoutubeExplode/issues/100
Added unit test case for large video that fails when this header isn't specified.
> Set HttpCompletionOption.ResponseHeadersRead on all HTTP requests

- YoutubeExplode/YoutubeClient.Video.cs
Change "'," to "});" when taking embeded video config.
I decided to use `});` since it seems more appropriate, because it starts taking config from `({'PLAYER_CONFIG': ` so it's only natural to seek for closing brackets.
Fixes #164
> Fix finding player config in GetVideoEmbedPageAsync

- YoutubeExplode.Tests/Data.cs
- YoutubeExplode.Tests/YoutubeClientUnitTests.cs
- YoutubeExplode/YoutubeClient.Channel.cs
- YoutubeExplode/YoutubeClient.Static.cs
This adds support for getting the username from a user URL.
`https://www.youtube.com/user/ProZD/` would return `ProZD`
>  Added parsing username from user url

- YoutubeExplode/Internal/Parsers/PlayerSourceParser.cs
Implemented the regex changes found here: https://github.com/rg3/youtube-dl/commit/2511eee215c2a66020ae927c86face826f48ba8e
Fixes #179. 
I've done a fair amount of testing on multiple videos that were broken before, and everything seems to be working fine.
I haven't tested how all the ciphers will react to the new entry point, just a random selection of normal and music videos. I've made the assumption that nothing else changed, so more testing may be required.
> Fix YouTube signature changes.

- YoutubeExplode/YoutubeClient.Playlist.cs
- YoutubeExplode/YoutubeClient.Search.cs
No idea what the previous regex was supposed to do, `(?=\<q>...)` seems malformed. It was probably overkill anyway as you can't actually save the double quote character in a keyword (though you can enter it and it will remain until the page is reloaded). You might be able to replace the `IsNullOrWhiteSpace` check with `IsNullOrEmpty` as well, you can't enter just a space.
I checked this [online](https://regex101.com), not by running the test suite.
edit: also, this isn't a valid playlist ID ([try it](https://youtube.com/watch?v=x2ZRoWQ0grU&list=RDEMNJhLy4rECJ_fG8NL-joqsg), should be `RDx2ZRoWQ0grU`):
https://github.com/Tyrrrz/YoutubeExplode/blob/847bb23bccff609bdcd61ef9ff22d4cc2f70b3c2/YoutubeExplode.Tests/TestData.cs#L109-L110
> Replace keyword extraction regex

- YoutubeExplode/ReverseEngineering/Responses/PlaylistResponse.cs
After getting some weird search results in some cases I decided to investigate.
Apparently the search method uses `WebUtility.HtmlEncode()` to encode the query parameter.
This method is used to encode for actual HTML content on webpages.
Scenario;
`string query = "björn rosenström ragnar"` => `queryEncoded = "bj&#246;rn rosenstr&#246;m ragnar"`. As you can see `ö` gets translated to `&#246;` which is the HTML representation of that character. This also has the unfortunate side-effect of cutting off the search query almost entirely after the first two letters (before it encounters the HTML encoded character). 
The URI representation would be `bj%C3%B6rn%20rosenstr%C3%B6m%20ragnar` which should be more correct in this context, as we are making an API call with query parameters in the URL. …
> Use Uri.Escape method instead of Html.Encode

- YoutubeExplode/Common/Engagement.cs
Noticed that `Engagement.ToString()` was showing the number of likes instead of dislikes.
> Fix showing likes instead of dislikes

- YoutubeExplode.DemoConsole/Program.cs
- `$ cd YoutubeExplode.DemoConsole &&  dotnet build && dotnet run`
- `$ Enter YouTube video ID or URL: https://www.youtube.com/watch?v=Qz3VBGo9jJU`
> Enter YouTube video ID or URL: https://www.youtube.com/watch?v=Qz3VBGo9jJU
Downloading stream: 720p / mp4... Completed ✓
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Shared/GitHub/YoutubeExplode/YoutubeExplode.DemoConsole/https:/www.youtube.com/watch?v=Qz3VBGo9jJU.mp4'.
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func\`2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
at …
> Fix IO and ArgumentException in DemoConsole when full YouTube URL and ID supplied

- YoutubeExplode.Tests/ChannelSpecs.cs
- YoutubeExplode.Tests/PlaylistSpecs.cs
- YoutubeExplode.Tests/SearchSpecs.cs
- YoutubeExplode.Tests/VideoSpecs.cs
- YoutubeExplode/Playlists/PlaylistClient.cs
- YoutubeExplode/ReverseEngineering/Responses/PlaylistResponse.cs
- YoutubeExplode/Search/SearchClient.cs
- YoutubeExplode/Videos/Video.cs
- YoutubeExplode/Videos/VideoClient.cs
This PR will enable us to get not only the Channel name (`Author` property) but the [ChannelId](https://github.com/Tyrrrz/YoutubeExplode/blob/10c9b63b2c0e2a66c1fb68a97b3d86d390e02b2b/YoutubeExplode/Channels/ChannelId.cs) too in these methods:
- [YoutubeClient.Channels.GetUploadsAsync(ChannelId id)](https://github.com/Tyrrrz/YoutubeExplode/blob/10c9b63b2c0e2a66c1fb68a97b3d86d390e02b2b/YoutubeExplode/Channels/ChannelClient.cs#L70)
- [YoutubeClient.Search.GetVideosAsync(string searchQuery)](https://github.com/Tyrrrz/YoutubeExplode/blob/10c9b63b2c0e2a66c1fb68a97b3d86d390e02b2b/YoutubeExplode/Search/SearchClient.cs#L28)
- [YoutubeClient.Playlists.GetVideosAsync(PlaylistId id)](https://github.com/Tyrrrz/YoutubeExplode/blob/516251580ec208f14765c23d854d4bce65ec86cf/YoutubeExplode/Playlists/Playlis …
> Add channelID in the video format

- YoutubeExplode.Tests/SearchSpecs.cs
- YoutubeExplode/Search/SearchClient.cs
Set `firstPage` to 1 if you want to skip the first page results from the
search pages and get everything after it.
Set `takePage` to 2 if you want to get the search results only from two
pages.
Closes #389
> Add search request limitation parameters

- YoutubeExplode.Tests/PlaylistSpecs.cs
- YoutubeExplode/Exceptions/PlaylistUnavailableException.cs
- YoutubeExplode/ReverseEngineering/Responses/PlaylistResponse.cs
Unfortunately we can't differentiate between the cases of a playlist being private, and one that doesn't exist. In both cases, the response returned is `400 : Bad Request`. This is intended as a fix for #445.
Closes #445
> Return more specific error message when playlist is unavailable

- YoutubeExplode/Internal/SegmentedHttpStream.cs
- YoutubeExplode/ReverseEngineering/YoutubeHttpClient.cs
- YoutubeExplode/Videos/Streams/StreamClient.cs
Following last comment on PR: https://github.com/Tyrrrz/YoutubeExplode/pull/448
Updated code so `_segmentSize` is nullable. (Will be null for Non-RateLimited video)
> Fix httpClient.GetStreamAsync segmentSize overflow issue

- YoutubeExplode.Tests/PlaylistSpecs.cs
- YoutubeExplode/AccessibilityExtensions.cs
- YoutubeExplode/Channels/ChannelClient.cs
- YoutubeExplode/Internal/Extensions/JsonElementExtensions.cs
- YoutubeExplode/Playlists/Playlist.cs
- YoutubeExplode/Playlists/PlaylistClient.cs
- YoutubeExplode/Playlists/PlaylistVideo.cs
- YoutubeExplode/ReverseEngineering/Responses/PlaylistResponse.cs
- YoutubeExplode/Search/SearchClient.cs
- YoutubeExplode/Videos/VideoClient.cs
This PR fixes the problems in the video search and playlist metadata functionality.
After investigating and searching for alternative methods to get videos from a query, I found out that you can get that info scraping directly from YouTube.
When making a search with YouTube and viewing the HTML source, there's an embedded JSON inside a script tag with a lot of useful information about the videos that appears in the results. This also appears when viewing a playlist.
I had to rewrite the Playlist/Search results logic from the lib to extract that JSON and make it to work, it also took me several hours to map every method with its corresponding JSON property.
Almost every data about a video/playlist can be obtained, except the following:
- Like count
- Dislike count
- Keywords
- Upload date …
> Fix video search and playlist metadata functionality

- YoutubeExplode.Tests/SearchSpecs.cs
- YoutubeExplode/ReverseEngineering/Responses/PlaylistResponse.cs
Youtube does not escape the query for the search call.  The added test fails without this change.
> Don't escape search query

- YoutubeExplode/Utils/Json.cs
Makes Json.Extract aware of whether or not the current character is inside of a string, and only count braces a that are not inside of sting.
This deals specifically with videos that have unmatched braces inside strings in their data. Example: watch?v=zSgiXGELjbc
> Ignore braces inside strings in `Json.Extract`

- YoutubeExplode/Videos/VideoController.cs
It looks like the issue that was causing the message was due to a new parameter YouTube looks for in their requests called `android_sdk_version`, as found out [here](https://github.com/iv-org/invidious/pull/3255). It looks like this just needs to be set to any valid Android SDK version number, and from my personal tests, it seems to have resolved the issue.
Closes #647
> Add 'androidSdkVersion' to request

- YoutubeExplode.Tests/ClosedCaptionSpecs.cs
- YoutubeExplode.Tests/StreamSpecs.cs
- YoutubeExplode.Tests/TestData/VideoIds.cs
- YoutubeExplode/Utils/Extensions/HttpExtensions.cs
- YoutubeExplode/Videos/Streams/MediaStream.cs
- YoutubeExplode/Videos/Streams/StreamClient.cs
- YoutubeExplode/YoutubeHttpHandler.cs
> Filter out streams with mismatched content length

- YoutubeExplode/YoutubeHttpHandler.cs
> Ignore invalid cookies supplied by YouTube

- YoutubeExplode.Tests/TestData/VideoIds.cs
- YoutubeExplode.Tests/VideoSpecs.cs
- YoutubeExplode/Bridge/SearchResponse.cs
Added code to ChannelId string to Json parse the Channeld ("browseId") string of a pay-to-watch video such as: https://www.youtube.com/show/SC5q_AUmH7GP_hCdqCc1QQXw
when these type of videos come up in a search query.
Closes #774
> Handle paid videos in search

- YoutubeExplode.Tests/PlaylistSpecs.cs
- YoutubeExplode/Bridge/IPlaylistData.cs
- YoutubeExplode/Bridge/PlaylistBrowseResponse.cs
- YoutubeExplode/Bridge/PlaylistNextResponse.cs
- YoutubeExplode/Playlists/Playlist.cs
- YoutubeExplode/Playlists/PlaylistClient.cs
Closes #356
// Provided solution wasn't actually a solution. Just a workaround.
---
Knowing the estimate videos count provided by the offical YouTube API without having to reiterate over the entire video collection is needed (especially when there are hundreds of videos in the playlist)
- Added `int VideosCount` to `Playlist`
- Added `int? VideosCount` to `IPlaylistData`, `PlaylistBrowseResponse`, `PlaylistNextResponse`
- Updated `PlaylistSpecs`-Tests
> Fetch video count in playlist metadata

- YoutubeExplode/YoutubeHttpHandler.cs
> Update cookie value in YoutubeHttpHandler.cs

- YoutubeExplode/Videos/ClosedCaptions/ClosedCaptionClient.cs
> Use the `IOS` client to pull closed captions, instead of `TVHTML5`

- YoutubeExplode.Converter.Tests/GeneralSpecs.cs
- YoutubeExplode.Converter/Converter.cs
- YoutubeExplode.Tests/StreamSpecs.cs
- YoutubeExplode.Tests/TestData/VideoIds.cs
- YoutubeExplode/Bridge/DashManifest.cs
- YoutubeExplode/Bridge/IStreamData.cs
- YoutubeExplode/Bridge/PlayerResponse.cs
- YoutubeExplode/Common/Language.cs
- YoutubeExplode/Utils/Extensions/JsonExtensions.cs
- YoutubeExplode/Videos/Streams/AudioOnlyStreamInfo.cs
- YoutubeExplode/Videos/Streams/IAudioStreamInfo.cs
- YoutubeExplode/Videos/Streams/MuxedStreamInfo.cs
- YoutubeExplode/Videos/Streams/StreamClient.cs
> Identify audio stream languages

- YoutubeExplode.Tests/SearchSpecs.cs
- YoutubeExplode/Bridge/SearchResponse.cs
because test is red and search is broken on the current master
> Fix playlist search response extraction

- YoutubeExplode/Utils/ProtoBuilder.cs
- YoutubeExplode/Utils/YoutubeParsingHelper.cs
- YoutubeExplode/Videos/VideoController.cs
As mentioned in https://github.com/Tyrrrz/YoutubeExplode/issues/794#issuecomment-2612699554 NewPipe fixed the issue by adding random visitor data to the InnerTube request. This is a translation from java of their fix.
Closes #794
> Update iOS client and add random visitor data to requests

- YoutubeExplode.Tests/VideoIdSpecs.cs
- YoutubeExplode/Videos/VideoId.cs
This PR only adds a missing case when trying to parse the video ID. I ran into it when using this video link:
https://youtu.be/watch?v=Fcds0_MrgNU
> Add missing case when trying to parse video ID

- YoutubeExplode/YoutubeHttpHandler.cs
To allow providing a custom Cookie like mentioned in the Authentication-part of the Readme:
```
using YoutubeExplode;
// Perform authentication and extract cookies
var cookies = ...;
// Cookie collection must be of type IReadOnlyList<System.Net.Cookie>
var youtube = new YoutubeClient(cookies);
``` 
That custom cookie must always have priority over the default/fallback cookie for this to work. I changed the order so to meet this requirement
Closes #909
> Fix custom cookies getting overwritten

- YoutubeExplode/Videos/Streams/StreamClient.cs
Related to problems in #853
Added ignoring for 403 Forbidden streams when getting manifests.
> Ignore 403 Forbidden streams when getting manifest
